backend:
  name: git-gateway
local_backend: true

media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - name: "site_info"
    label: "Site Info"
    delete: false
    editor:
      preview: false
    files:
      - name: "hero"
        label: "Hero"
        file: "meta/hero.yml"
        description: "Hero"
        fields:
          - name: hero_content
            label: Hero
            label_singular: "Hero"
            widget: object
            fields:
              - {label: "Hero Image", name: "hero_image", widget: "image"}
              - { label: "Hero Text", name: "hero_text", widget: "text"}
              - label: "Button One"
                name: "button_one"
                widget: "object"
                hint: "The first button"
                fields:
                  - label: "Text"
                    name: "button_name"
                    widget: "string"
                    hint: "Button Text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    hint: "Button Link"
              - label: "Button Two"
                name: "button_two"
                widget: "object"
                hint: "The second button"
                fields:
                  - label: "Text"
                    name: "button_name"
                    widget: "string"
                    hint: "Button Text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    hint: "Button Link"
              
      - name: "tags"
        label: "Categories"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Categories
            label_singular: "Category"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the category"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Category name for displaying on the site"
      - name: "collections"
        label: "Collections"
        file: "meta/collections.yml"
        description: "List of Collections"
        fields:
          - name: collections
            label: "Collections"
            label_singular: "Collection"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the collection"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Collection name for displaying on the site"
      - name: "social"
        label: "Social Media"
        file: "meta/social.yml"
        description: "Social Media Links"
        fields:
          - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
          - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
          - { label: 'YouTube', name: 'youtube', widget: 'string', required: false }
          - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }    
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      slug: '/'
      editor:
        preview: false
      file: "src/pages/content/home.md"
      fields:
        - { label: "Slug", name: slug, widget: hidden, default: "/"}
        - { label: "Body", name: "body", widget: markdown}
        - label: 'Slider Block'
          name: "slider"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Thumbnail", name: "thumbnail", widget: "image"}
            - { label: "Link", name: "link", widget: string, required: false}
    - label: "About"
      name: "about"
      slug: '/'
      editor:
        preview: false
      file: "src/pages/content/about.md"
      fields:
        - { label: "URL", name: url, widget: hidden, default: "/about"}
        - label: "Top Section"
          name: "top_section"
          widget: object
          fields:
            - {label: "Title", name: "title", widget: string}
            - {label: "Text Block", name: "text_block", widget: text}
            - {label: "Hero Image", name: "hero_image", widget: image}
            - label: "Button"
              name: "button" 
              widget: object
              fields:
                - {label: "Button Text", name: "button_text", widget: string}
                - {label: "Button Link", name: "button_link", widget: string}
        - label: "Blocks"
          name: "blocks"
          widget: list
          fields:
              - label: "Block"
                name: "block"
                widget: object
                fields:
                  - { label: "Icon", name: "icon", widget: image}
                  - { label: "Text", name: "text", widget: text}

        - { label: "Body", name: "body", widget: markdown}
    - label: "Overview"
      name: "overview"
      slug: '/'
      editor:
        preview: false
      file: "src/pages/content/overview.md"
      fields:
        - label: "Top Section"
          name: "top_section"
          widget: object
          fields:
            - {label: "Title", name: "title", widget: string}
            - {label: "Hero Image", name: "hero_image", widget: image}
        - label: "Blocks"
          name: "blocks"
          widget: list
          limit: 3
          fields:
              - label: "Block"
                name: "block"
                widget: object
                fields:
                  - { label: "Icon", name: "icon", widget: image}
                  - { label: "Title", name: "title", widget: string}
                  - { label: "Sub Title", name: "subtitle", widget: string}
                  - { label: "Text", name: "text", widget: text}
                  - { label: "URL", name: "url", widget: string}
    - label: "Contact"
      name: "contact"
      editor:
        preview: false
      file: "src/pages/content/contact.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { 
            label: "Publish Date", 
            name: "date", 
            widget: 'datetime',
            format: 'ddd MMM D, YYYY LT',
            date_format: 'ddd MMM D, YYYY',
            dateFormat: 'ddd MMM D, YYYY',
            time_format: 'hh:mm A',
            timeFormat: 'hh:mm A', 
            }
        - { label: "Body", name: "body", widget: "markdown"}
        - { label: "Address", name: "address", widget: "text"}
        - { label: "E-Mail", name: "email", widget: "string"}
        - { label: "Phone", name: "phone", widget: "string"}
    - label: "Privacy Policy"
      name: "privacy"
      file: "src/pages/content/privacy.md"
      fields:
        - { label: "Date Updated", name: "date", widget: "datetime"}
        - { label: "Body", name: "body", widget: markdown}
    - label: "Virtual Industry Day"
      name: "vi_day"
      slug: '/virtual-industry-day'
      editor:
        preview: false
      file: "src/pages/content/viday.md"
      fields:
        - { label: "Title", name: 'title', widget: string}
        - {
          label: 'Event Date',
          name: 'date',
          widget: 'datetime',
          format: 'ddd MMM D, YYYY LT',
          date_format: 'ddd MMM D, YYYY',
          dateFormat: 'ddd MMM D, YYYY',
          time_format: 'hh:mm A',
          timeFormat: 'hh:mm A',
        }
        - { label: "Vimeo Code", name: "vimeo_code", widget: string}
        - { label: "Sub Title", name: "sub_title", widget: string}
        - { label: "Text", name: "text", widget: text}
  - name: blog
    label: News
    label_singular: News Article
    folder: src/blog-posts
    create: true
    preview_path: 'news/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured', name: 'featured', widget: 'select', options: ["Yes", "No"], default: "No"}
      - { label: "Featured Image", name: "featured_image", widget: image}
      - { label: "Excerpt", name: "excerpt", widget: text}
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false}
      - { label: 'Pre Title', name: 'pre_title', widget: 'string', required: false}
      - { label: "Pre Text", name: "pre_text", widget: text, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      -   label: "Information"
          name: "information"
          widget: object
          fields:
            - {label: "Value", name: "value", widget: string, required: false}
            - {label: "Type", name: "type", widget: string, required: false}
            - {label: "Release Date", name: "release", widget: string, required: false}
      -   label: "Changelog"
          name: "changelog"
          widget: list
          fields:
            - {label: "Value", name: "value", widget: string}
      -   label: "Important Links"
          name: "impLinks"
          widget: list
          fields:
            - {label: "Link Text", name: "text", widget: string}
            - {label: "Link URL", name: "url", widget: string}
      - { label: 'Mobilize Link', name: 'mobLink', widget: string, required: false}
      - { label: 'File', name: 'file', widget: 'file', required: false }
      - label: Categories
        label_singular: "Category"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: Collections
        label_singular: "Collection"
        name: "collections"
        widget: list
        summary: "{{fields.collection}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "collections"
          searchFields:
            - "collections.*.name"
          displayFields:
            - "collections.*.name"
          valueField: "collections.*.slug"
  - name: events
    label: Events
    label_singular: Event
    folder: src/events
    create: true
    preview_path: '/event/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Event Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured', name: 'featured', widget: 'select', options: ["Yes", "No"], default: "No"}
      - { label: "Featured Image", name: "featured_image", widget: image}
      - { label: "Excerpt", name: "excerpt", widget: text}
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false}
      - { label: 'Pre Title', name: 'pre_title', widget: 'string', required: false}
      - { label: "Pre Text", name: "pre_text", widget: text, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      -   label: "Information"
          name: "information"
          widget: object
          fields:
            - {label: "Value", name: "value", widget: string, required: false}
            - {label: "Type", name: "type", widget: string, required: false}
            - {label: "Release Date", name: "release", widget: string, required: false}
      -   label: "Changelog"
          name: "changelog"
          widget: list
          fields:
            - {label: "Value", name: "value", widget: string}
      -   label: "Important Links"
          name: "impLinks"
          widget: list
          fields:
            - {label: "Link Text", name: "text", widget: string}
            - {label: "Link URL", name: "url", widget: string}
      - { label: 'Mobilize Link', name: 'mobLink', widget: string, required: false}
      - { label: 'File', name: 'file', widget: 'file', required: false }
      - label: Categories
        label_singular: "Category"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: Collections
        label_singular: "Collection"
        name: "collections"
        widget: list
        summary: "{{fields.collection}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "collections"
          searchFields:
            - "collections.*.name"
          displayFields:
            - "collections.*.name"
          valueField: "collections.*.slug"
  - name: exchange-opps
    label: Opportunities
    label_singular: Opportunity
    folder: src/exchange-opps
    create: true
    preview_path: '/opportunity/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured', name: 'featured', widget: 'select', options: ["Yes", "No"], default: "No"}
      - { label: "Featured Image", name: "featured_image", widget: image}
      - { label: "Excerpt", name: "excerpt", widget: text}
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false}
      - { label: 'Pre Title', name: 'pre_title', widget: 'string', required: false}
      - { label: "Pre Text", name: "pre_text", widget: text, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      -   label: "Information"
          name: "information"
          widget: object
          fields:
            - {label: "Value", name: "value", widget: string, required: false}
            - {label: "Type", name: "type", widget: string, required: false}
            - {label: "Release Date", name: "release", widget: string, required: false}
      -   label: "Changelog"
          name: "changelog"
          widget: list
          fields:
            - {label: "Value", name: "value", widget: string}
      -   label: "Important Links"
          name: "impLinks"
          widget: list
          fields:
            - {label: "Link Text", name: "text", widget: string}
            - {label: "Link URL", name: "url", widget: string}
      - { label: 'Mobilize Link', name: 'mobLink', widget: string, required: false}
      - { label: 'File', name: 'file', widget: 'file', required: false }
      - label: Categories
        label_singular: "Category"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: Collections
        label_singular: "Collection"
        name: "collections"
        widget: list
        summary: "{{fields.collection}}"
        field:
          label: Categories
          name: tag
          widget: relation
          collection: "site_info"
          file: "collections"
          searchFields:
            - "collections.*.name"
          displayFields:
            - "collections.*.name"
          valueField: "collections.*.slug"